{{- $apiSecret := (randAlphaNum 32) | b64enc | quote }}

{{- $secretName := printf "%s-%s" .Release.Name "api-secret" }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if $secret }}
{{- $apiSecret = index $secret.data "api-secret-key" }}
{{- end -}}


apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{ include "cas-airflow.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  api-secret-key: {{ $apiSecret }}
