apiVersion: v2
name: cas-airflow-dag-trigger
description: A Helm chart for triggering remote DAGs on an existing airflow instance
type: application
version: 1.2.1  # Changing this requires updating the image tag in .github/workflows/release.yaml
